spring.config.import=optional:file:.env[.properties]

# Exchange y Queue
rabbitmq.exchange.commercial=${RABBITMQ_EXCHANGE_COMMERCIAL: commercial.exchange}
rabbitmq.queue.purchase=${RABBITMQ_QUEUE_PURCHASE: purchase.queue}
rabbitmq.routing-key.purchase=${RABBITMQ_ROUTING_KEY_PURCHASE: purchase.received}

# Sales RabbitMQ - Create
rabbitmq.exchange.sales-create=${RABBITMQ_EXCHANGE_SALES_CREATE:sales.create.exchange}
rabbitmq.queue.sales-create-request=${RABBITMQ_QUEUE_SALES_CREATE_REQUEST:sales.create.request.queue}
rabbitmq.routing-key.sales-create-request=${RABBITMQ_ROUTING_KEY_SALES_CREATE_REQUEST:sales.create.request}

# Sales RabbitMQ - Update
rabbitmq.exchange.sales-update=${RABBITMQ_EXCHANGE_SALES_UPDATE:sales.update.exchange}
rabbitmq.queue.sales-update-request=${RABBITMQ_QUEUE_SALES_UPDATE_REQUEST:sales.update.request.queue}
rabbitmq.routing-key.sales-update-request=${RABBITMQ_ROUTING_KEY_SALES_UPDATE_REQUEST:sales.update.request}

# Sales RabbitMQ - Patch
rabbitmq.exchange.sales-patch=${RABBITMQ_EXCHANGE_SALES_PATCH:sales.patch.exchange}
rabbitmq.queue.sales-patch-request=${RABBITMQ_QUEUE_SALES_PATCH_REQUEST:sales.patch.request.queue}
rabbitmq.routing-key.sales-patch-request=${RABBITMQ_ROUTING_KEY_SALES_PATCH_REQUEST:sales.patch.request}

# Sales RabbitMQ - Delete
rabbitmq.exchange.sales-delete=${RABBITMQ_EXCHANGE_SALES_DELETE:sales.delete.exchange}
rabbitmq.queue.sales-delete-request=${RABBITMQ_QUEUE_SALES_DELETE_REQUEST:sales.delete.request.queue}
rabbitmq.routing-key.sales-delete-request=${RABBITMQ_ROUTING_KEY_SALES_DELETE_REQUEST:sales.delete.request}
