spring.config.import=optional:file:.env[.properties]

# Exchange y Queue
rabbitmq.exchange.commercial=${RABBITMQ_EXCHANGE_COMMERCIAL: commercial.exchange}
rabbitmq.queue.purchase=${RABBITMQ_QUEUE_PURCHASE: purchase.queue}
rabbitmq.routing-key.purchase=${RABBITMQ_ROUTING_KEY_PURCHASE: purchase.received}